In [1]:
import numpy as np
from scipy.io import loadmat
from sklearn.neighbors import NearestNeighbors

In [2]:
# Load all of the saved files
train_feat = np.loadtxt('train_feat.gzip', dtype = 'float')
gallery_feat = np.loadtxt('gallery_feat.gzip', dtype = 'float')
query_feat = np.loadtxt('query_feat.gzip', dtype = 'float')
val_feat = np.loadtxt('val_feat.gzip', dtype = 'float')
train_noval_feat = np.loadtxt('train_noval_feat.gzip', dtype = 'float')
train_labels = np.loadtxt('train_labels.gzip', dtype = 'uint16')
gallery_labels = np.loadtxt('gallery_labels.gzip', dtype = 'uint16')
query_labels = np.loadtxt('query_labels.gzip', dtype = 'uint16')
val_labels = np.loadtxt('val_labels.gzip', dtype = 'uint16')
train_noval_labels = np.loadtxt('train_noval_labels.gzip', dtype = 'uint16')
#train_filelist = np.loadtxt('train_filelist.gzip', dtype = 'uint16')
#gallery_filelist = np.loadtxt('gallery_filelist.gzip', dtype = 'uint16')
#query_filelist = np.loadtxt('query_filelist.gzip', dtype = 'uint16')
#val_filelist = np.loadtxt('val_filelist.gzip', dtype = 'uint16')
#train_noval_filelist = np.loadtxt('train_noval_filelist.gzip', dtype = 'uint16')
train_camId = np.loadtxt('train_camId.gzip', dtype = 'uint16') # uint8
gallery_camId = np.loadtxt('gallery_camId.gzip', dtype = 'uint16')
query_camId = np.loadtxt('query_camId.gzip', dtype = 'uint16')
val_camId = np.loadtxt('val_camId.gzip', dtype = 'uint16')
train_noval_camId = np.loadtxt('train_noval_camId.gzip', dtype = 'uint16')

In [3]:
# Function that takes as input an index that refers to a query image
# and returns the gallery without the unnecessary pictures in it
# Remove the pictures from the gallery that have the same label and are taken by the same camera as out QUERY[index]
# picture in the query array
def get_removed_gallery (index):
    selected_indices = np.logical_not(np.logical_and(gallery_camId == query_camId[index], gallery_labels == gallery_labels[index]))
    return gallery_feat[selected_indices, :], gallery_labels[selected_indices]

In [4]:
a, b = get_removed_gallery(0)
print (a, a.shape, b, b.shape)

[[1.05525982 0.29310364 0.19821346 ... 0.00684856 0.0561235  0.01862506]
 [0.98361254 0.33195475 0.26549727 ... 0.02350602 0.08491972 0.00514889]
 [0.82696682 0.39545193 0.13419056 ... 0.02507348 0.06063982 0.03505545]
 ...
 [0.01961832 0.17617127 0.54575312 ... 0.33026204 0.93925601 0.56220758]
 [0.05719076 0.60635394 0.58300596 ... 0.40994745 1.37061644 0.55975795]
 [0.07245111 0.51656747 0.59082419 ... 0.60488421 1.05610693 0.72939718]] (5328, 2048) [   3    3    3 ... 1463 1463 1463] (5328,)


In [5]:
# k nearest neighbours implementation
k = 1
print (query_labels.shape)
accuracies = np.zeros((query_labels.shape[0]))
print (accuracies, accuracies.shape)
for i in range (0, query_labels.shape[0], 1):
    gallery_feat_removed, gallery_labels_removed = get_removed_gallery (i)
    nbrs = NearestNeighbors(n_neighbors=k).fit(gallery_feat_removed)
    distances, indices = nbrs.kneighbors(query_feat[i:i+1, :])
    print(gallery_labels_removed[indices], query_labels[i])
    is_same_label = (np.ones((k))*query_labels[i] == gallery_labels_removed[indices])
    accuracy = np.sum(is_same_label)/k
    print (accuracy)
    accuracies[i]=accuracy
    
print (accuracies.mean())

(1400,)
[0. 0. 0. ... 0. 0. 0.] (1400,)
[[3]] 3
1.0
[[3]] 3
1.0
[[6]] 6
1.0
[[6]] 6
1.0
[[7]] 7
1.0
[[7]] 7
1.0
[[11]] 11
1.0
[[11]] 11
1.0
[[14]] 14
1.0
[[14]] 14
1.0
[[17]] 17
1.0
[[17]] 17
1.0
[[22]] 22
1.0
[[22]] 22
1.0
[[28]] 28
1.0
[[28]] 28
1.0
[[30]] 30
1.0
[[30]] 30
1.0
[[32]] 32
1.0
[[32]] 32
1.0
[[33]] 33
1.0
[[33]] 33
1.0
[[34]] 34
1.0
[[34]] 34
1.0
[[35]] 35
1.0
[[35]] 35
1.0
[[38]] 38
1.0
[[38]] 38
1.0
[[40]] 40
1.0
[[40]] 40
1.0
[[41]] 41
1.0
[[41]] 41
1.0
[[42]] 42
1.0
[[42]] 42
1.0
[[45]] 45
1.0
[[45]] 45
1.0
[[47]] 47
1.0
[[47]] 47
1.0
[[51]] 51
1.0
[[51]] 51
1.0
[[54]] 54
1.0
[[54]] 54
1.0
[[55]] 55
1.0
[[55]] 55
1.0
[[58]] 58
1.0
[[58]] 58
1.0
[[60]] 60
1.0
[[60]] 60
1.0
[[62]] 62
1.0
[[62]] 62
1.0
[[68]] 68
1.0
[[68]] 68
1.0
[[69]] 69
1.0
[[69]] 69
1.0
[[70]] 70
1.0
[[70]] 70
1.0
[[72]] 72
1.0
[[72]] 72
1.0
[[74]] 74
1.0
[[74]] 74
1.0
[[76]] 76
1.0
[[76]] 76
1.0
[[77]] 77
1.0
[[77]] 77
1.0
[[78]] 78
1.0
[[78]] 78
1.0
[[80]] 80
1.0
[[80]] 80
1.0
[[81]] 81
1.0
[[81]]

KeyboardInterrupt: 

In [ ]:



well_predicted = gallery_labels_removed[indices, :] == np.ones((k))*query_labels[0]
print (well_predicted, well_predicted.shape)
precision_or_recall = np.sum(well_predicted)/k
print (precision_or_recall)

In [ ]:
print (query_feat.dtype, query_feat.max())
print (gallery_feat, gallery_feat.shape)
print (query_feat, query_feat.shape)

In [ ]:
X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
nbrs = NearestNeighbors(n_neighbors=5, algorithm='ball_tree').fit(X)
distances, indices = nbrs.kneighbors([[0, 1], [0,0]])
print(indices)
print (distances)

In [ ]:
k = 5
nbrs = NearestNeighbors(n_neighbors=k).fit(gallery_feat)
distances, indices = nbrs.kneighbors(query_feat)
print(indices, indices.shape)
print (distances, distances.shape)